#!/bin/bash
menunya(){
menu="
PILIHAN MENU :
1. run server development mode
2. buka localhost:3000
0. keluar
"
echo "${menu}"
echo -n "Masukkan Pilihannya: "

}
menunya

LOCAL_SERVER(){
  echo "mulain menjalankan server"
  nodemon server.js & webpack --mode development --watch
}

OPEN_WEB(){
  ./open_web
}

while :
do
read choice
case $choice in
  1)  LOCAL_SERVER ;;
  2)  OPEN_WEB ;;
  0)  exit;;
  *)  echo "hemmm , lihat pilihan di menunya"
esac
  menunya
done